---
services:
  reverse-proxy:
    image: traefik:v3.0
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket to watch for Traefik
      - ./config/:/etc/traefik/:ro
      - ./certs/:/var/traefik/certs/:rw

    networks:
      - traefik-network
    restart: unless-stopped

  frontend:
    build:
      context: ./portfolio-front
      args:
        - VITE_SERVER_URL=https://api.ozzurep.tech
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`ozzurep.tech`)'
      - 'traefik.http.services.frontend.loadbalancer.server.port=80'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls=true'
      - 'traefik.http.routers.frontend.tls.certresolver=cloudflare'
      - 'traefik.http.middlewares.frontend-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.frontend-redirect.redirectscheme.permanent=true'
      - 'traefik.http.routers.frontend-http.rule=Host(`ozzurep.tech`)'
      - 'traefik.http.routers.frontend-http.entrypoints=web'
      - 'traefik.http.routers.frontend-http.middlewares=frontend-redirect'

    environment:
      - VITE_SERVER_URL=https://api.ozzurep.tech
    restart: unless-stopped
    networks:
      - traefik-network

  backend:
    build: ./portfolio-back
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.tls.certresolver=cloudflare'
      - 'traefik.http.middlewares.backend-redirect.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.backend-redirect.redirectscheme.permanent=true'
      - 'traefik.http.routers.backend-http.rule=Host(`api.ozzurep.tech`)'
      - 'traefik.http.routers.backend-http.entrypoints=web'
      - 'traefik.http.routers.backend-http.middlewares=backend-redirect'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*'
      - 'traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://ozzurep.tech,http://ozzurep.tech'
      - 'traefik.http.middlewares.cors.headers.accesscontrolmaxage=100'
      - 'traefik.http.middlewares.cors.headers.addvaryheader=true'
      - 'traefik.http.routers.backend.middlewares=cors'
    environment:
      - DATABASE_URL=postgresql://ozzu:marij@postgres:5432/portfolio
      - IS_LOCAL=true
    restart: unless-stopped
    networks:
      - traefik-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ozzu
      POSTGRES_PASSWORD: marij
      POSTGRES_DB: portfolio
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-network
    labels:
      - 'traefik.enable=false'

networks:
  traefik-network:
    driver: bridge

volumes:
  postgres_data:
  # traefik-certs:
  #   driver: local
  # traefik-logs:
  #   driver: local
  #
