global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO # Changed from DEBUG to reduce noise
  format: json # Optional: for better log parsing

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true # Permanent redirect
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: cloudflare
        # Optional: Minimum TLS version
        options: default

# Add TLS Options for stronger security
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

certificatesResolvers:
  cloudflare:
    acme:
      email: peruzzoarthur@gmail.com
      storage: /var/traefik/certs/cloudflare-acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - '1.1.1.1:53'
          - '8.8.8.8:53'

# Secure API Access
api:
  dashboard: true
  insecure: false # Disable insecure access
  # debug: false    # Disable debug mode in production

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false

serversTransport:
  insecureSkipVerify: false # Be cautious with this setting
