---
global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: cloudflare

certificatesResolvers:
  cloudflare:
    acme:
      email: peruzzoarthur@gmail.com
      storage: /var/traefik/certs/cloudflare-acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - '1.1.1.1:53'
          - '8.8.8.8:53'

api:
  dashboard: true
  insecure: true
  debug: true

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    network: traefik-network # Optional; Only use the "proxy" Docker network, even if containers are on multiple networks.
serversTransport:
  insecureSkipVerify: true
