services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - '--api.insecure=true'
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.email=ozzu@ozzurep.tech'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
      # - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--log.level=ERROR'
      - '--log.filePath=/logs/traefik.log'
      # HTTP to HTTPS redirect
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      # Enable ping
      - '--ping'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
      - traefik-logs:/logs
    networks:
      - traefik-network
    restart: always
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']

  frontend:
    build:
      context: ./portfolio-front
      args:
        - VITE_SERVER_URL=https://api.ozzurep.tech
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=Host(`ozzurep.tech`)'
      - 'traefik.http.services.frontend.loadbalancer.server.port=80'
      - 'traefik.http.routers.frontend.entrypoints=websecure'
      - 'traefik.http.routers.frontend.tls=true'
      - 'traefik.http.routers.frontend.tls.certresolver=myresolver'
    environment:
      - VITE_SERVER_URL=https://api.ozzurep.tech
    restart: unless-stopped
    networks:
      - traefik-network

  backend:
    build: ./portfolio-back
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`api.ozzurep.tech`)'
      - 'traefik.http.services.backend.loadbalancer.server.port=3000'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls=true'
      - 'traefik.http.routers.backend.tls.certresolver=myresolver'
      - 'traefik.http.routers.backend.middlewares=cors@docker'
    environment:
      - DATABASE_URL=postgresql://ozzu:marij@postgres:5432/portfolio
      - IS_LOCAL=true
    restart: unless-stopped
    networks:
      - traefik-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ozzu
      POSTGRES_PASSWORD: marij
      POSTGRES_DB: portfolio
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik-network
    labels:
      - 'traefik.enable=false'

networks:
  traefik-network:
    driver: bridge

volumes:
  postgres_data:
  letsencrypt:
  traefik-logs:
